export default {
  SELECT_ACCEPT_PENDING: id => id,
  FETCH_ACCEPT_PENDINGS: null,
  FETCH_ACCEPT_PENDINGS_SUCCESS: payload => payload,
  FETCH_NOTIFICATIONS: null,
  FETCH_NOTIFICATIONS_SUCCESS: payload => payload,
  FETCH_REQUEST_PENDINGS: null,
  FETCH_REQUEST_PENDINGS_SUCCESS: payload => payload
}
