const def = action => `COMPANY/NOTIFICATION/${action}`
export const SELECT_ACCEPT_PENDING = def('SELECT_ACCEPT_PENDING')
export const FETCH_ACCEPT_PENDINGS = def('FETCH_ACCEPT_PENDINGS')
export const FETCH_ACCEPT_PENDINGS_SUCCESS = def(
  'FETCH_ACCEPT_PENDINGS_SUCCESS'
)
export const FETCH_NOTIFICATIONS = def('FETCH_NOTIFICATIONS')
export const FETCH_NOTIFICATIONS_SUCCESS = def('FETCH_NOTIFICATIONS_SUCCESS')
export const ADD_NOTIFICATION = def('ADD_NOTIFICATION')
export const ADD_NOTIFICATION_SUCCESS = def('ADD_NOTIFICATION_SUCCESS')
export const FETCH_REQUEST_PENDINGS = def('FETCH_REQUEST_PENDINGS')
export const FETCH_REQUEST_PENDINGS_SUCCESS = def(
  'FETCH_REQUEST_PENDINGS_SUCCESS'
)
export const ACCEPT_AGENT = def('ACCEPT_AGENT')
export const ACCEPT_AGENT_SUCCESS = def('ACCEPT_AGENT_SUCCESS')
export const CANCEL_REQUEST_AGENT = def('CANCEL_REQUEST_AGENT')
export const CANCEL_REQUEST_AGENT_SUCCESS = def('CANCEL_REQUEST_AGENT_SUCCESS')
export const REJECT_REQUEST_AGENT = def('REJECT_REQUEST_AGENT')
export const REJECT_REQUEST_AGENT_SUCCESS = def('REJECT_REQUEST_AGENT_SUCCESS')
