image: docker:latest
services:
- docker:dind

stages:
- build

variables:
  SERVER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-server:
  stage: build
  script:
    - docker build -t $SERVER_TEST_IMAGE ./server
    - docker push $SERVER_TEST_IMAGE