# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: docker-image:tag

image: paiboon15721/node-docker-compose
pipelines:
  branches:
    production:
      - step:
          script:
            - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            - docker-compose build
            - docker-compose push
            - docker logout

options:
  docker: true