version: '3.2'
services:
  frontend:
    build: ./client
    depends_on:
      - tourapp-api
    ports:
      - '8080:80'
      - '4000:4000'
  tourapp-api:
    build: ./server
    depends_on:
      - redis-db
      - mongo-db
    environment:
      - MONGO_DB_HOST=mongo-db
      - REDIS_HOST=redis-db
  redis-db:
    image: redis:alpine
    volumes:
      - redis-data:/data
  mongo-db:
    image: mongo
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
  redis-data: