export const SIGN_IN_SUCCESS = 'sign_in_success'
export const SIGN_OUT_SUCCESS = 'sign_out_success'
export const SIGN_UP_SUCCESS = 'sign_up_success'
export const SIGN_IN_FAIL = 'sign_in_fail'
export const SIGN_UP_FAIL = 'sign_up_fail'
export const HIDE_AUTH_NOTIFICATION = 'hide_auth_notification'

export const FETCH_PKGS_SUCCESS = 'fetch_pkgs_success'
export const OPEN_ADD_BOOKING_MODAL = 'open_add_booking_modal'
export const CLOSE_ADD_BOOKING_MODAL = 'close_add_booking_modal'
export const ADD_BOOKING_SUCCESS = 'add_booking_success'
export const HIDE_BOOKING_NOTIFICATION = 'hide_booking_notification'

export const FETCH_COMPANIES_SUCCESS = 'fetch_companies_success'
export const REQUEST_COMPANY_SUCCESS = 'request_company_success'
export const REQUEST_COMPANY_FAIL = 'request_company_fail'
export const ACCEPT_COMPANY_SUCCESS = 'accept_company_success'
export const REJECT_REQUEST_COMPANY_SUCCESS = 'reject_request_company_success'
export const OPEN_REQUEST_COMPANY_MODAL = 'open_request_company_modal'
export const CLOSE_REQUEST_COMPANY_MODAL = 'close_request_company_modal'
export const CANCEL_REQUEST_COMPANY_SUCCESS = 'cancel_request_company_success'
export const OPEN_DELETE_COMPANY_MODAL = 'open_delete_company_modal'
export const CLOSE_DELETE_COMPANY_MODAL = 'close_delete_company_modal'
export const DELETE_COMPANY_SUCCESS = 'delete_company_success'
export const HIDE_COMPANY_NOTIFICATION = 'hide_company_notification'

export const TOGGLE_PROFILE_MENU = 'toggle_profile_menu'
export const TOGGLE_NOTIFICATION_GEM = 'toggle_notification_gem'
export const TOGGLE_ACCEPT_PENDING_GEM = 'toggle_accept_pending_gem'
export const TOGGLE_REQUEST_PENDING_GEM = 'toggle_request_pending_gem'
export const HIDE_ALL_GEM = 'hide_all_gem'
export const FETCH_REQUEST_PENDINGS_SUCCESS = 'fetch_request_pendings_success'
export const FETCH_ACCEPT_PENDINGS_SUCCESS = 'fetch_accept_pendings_success'
export const FETCH_NOTIFICATIONS_SUCCESS = 'fetch_notifications_success'
