export const FETCH_PKGS_SUCCESS = 'fetch_pkgs_success'
export const DELETE_PKG_SUCCESS = 'delete_pkg_success'
export const ADD_PKG_SUCCESS = 'add_pkg_success'
export const OPEN_ADD_PKG_MODAL = 'open_add_pkg_modal'
export const CLOSE_ADD_PKG_MODAL = 'close_add_pkg_modal'
export const OPEN_DELETE_PKG_MODAL = 'open_delete_pkg_modal'
export const CLOSE_DELETE_PKG_MODAL = 'close_delete_pkg_modal'
export const HIDE_PKG_NOTIFICATION = 'hide_pkg_notification'
