export const SIGN_IN_SUCCESS = 'sign_in_success'
export const SIGN_OUT_SUCCESS = 'sign_out_success'
export const SIGN_UP_SUCCESS = 'sign_up_success'
export const SIGN_IN_FAIL = 'sign_in_fail'
export const SIGN_UP_FAIL = 'sign_up_fail'
export const HIDE_AUTH_NOTIFICATION = 'hide_auth_notification'

export const FETCH_BOOKINGS_SUCCESS = 'fetch_bookings_success'
export const BOOKING_NOTIFY = 'booking_notify'

export const FETCH_PKGS_SUCCESS = 'fetch_pkgs_success'
export const DELETE_PKG_SUCCESS = 'delete_pkg_success'
export const ADD_PKG_SUCCESS = 'add_pkg_success'
export const OPEN_ADD_PKG_MODAL = 'open_add_pkg_modal'
export const CLOSE_ADD_PKG_MODAL = 'close_add_pkg_modal'
export const OPEN_EDIT_PKG_MODAL = 'open_edit_pkg_modal'
export const CLOSE_EDIT_PKG_MODAL = 'close_edit_pkg_modal'
export const EDIT_PKG_SUCCESS = 'edit_pkg_success'
export const OPEN_DELETE_PKG_MODAL = 'open_delete_pkg_modal'
export const CLOSE_DELETE_PKG_MODAL = 'close_delete_pkg_modal'
export const HIDE_PKG_NOTIFICATION = 'hide_pkg_notification'

export const FETCH_AGENTS_SUCCESS = 'fetch_agents_success'
export const DELETE_AGENT_SUCCESS = 'delete_agent_success'
export const REQUEST_AGENT_SUCCESS = 'request_agent_success'
export const CANCEL_REQUEST_AGENT_SUCCESS = 'cancel_request_agent_success'
export const REQUEST_AGENT_FAIL = 'request_agent_fail'
export const OPEN_REQUEST_AGENT_MODAL = 'open_request_agent_modal'
export const CLOSE_REQUEST_AGENT_MODAL = 'close_request_agent_modal'
export const OPEN_DELETE_AGENT_MODAL = 'open_delete_agent_modal'
export const CLOSE_DELETE_AGENT_MODAL = 'close_delete_agent_modal'
export const OPEN_RESET_PRICE_MODAL = 'open_reset_price_modal'
export const CLOSE_RESET_PRICE_MODAL = 'close_reset_price_modal'
export const FETCH_AGENT_CONTRACT_RATES_SUCCESS =
  'fetch_agent_contract_rates_success'

export const OPEN_CONTRACT_RATE_MODAL = 'open_contract_rate_modal'
export const CLOSE_CONTRACT_RATE_MODAL = 'close_contract_rate_modal'
export const OPEN_OFFER_SPECIAL_PRICE_MODAL = 'open_offer_special_price_modal'
export const CLOSE_OFFER_SPECIAL_PRICE_MODAL = 'close_offer_special_price_modal'
export const OFFER_SPECIAL_PRICE_SUCCESS = 'offer_special_price_success'
export const RESET_PRICE_SUCCESS = 'reset_price_success'
export const HIDE_AGENT_NOTIFICATION = 'hide_agent_notification'

export const TOGGLE_PROFILE_MENU = 'toggle_profile_menu'
export const TOGGLE_NOTIFICATION_GEM = 'toggle_notification_gem'
export const TOGGLE_ACCEPT_PENDING_GEM = 'toggle_accept_pending_gem'
export const TOGGLE_REQUEST_PENDING_GEM = 'toggle_request_pending_gem'
export const HIDE_ALL_GEM = 'hide_all_gem'
export const FETCH_REQUEST_PENDINGS_SUCCESS = 'fetch_request_pendings_success'
export const FETCH_ACCEPT_PENDINGS_SUCCESS = 'fetch_accept_pendings_success'
export const FETCH_NOTIFICATIONS_SUCCESS = 'fetch_notifications_success'
