const def = action => `COMPANY/BOOKING_SUMMARY/${action}`
export const FETCH_BOOKING_SUMMARY = def('FETCH_BOOKING_SUMMARY')
export const FETCH_BOOKING_SUMMARY_SUCCESS = def(
  'FETCH_BOOKING_SUMMARY_SUCCESS'
)
