const def = action => `COMPANY/BOOKING_SUMMARY/${action}`
export const FETCH_BOOKINGS_SUMMARY = def('FETCH_BOOKINGS_SUMMARY')
export const FETCH_BOOKINGS_SUMMARY_SUCCESS = def(
  'FETCH_BOOKINGS_SUMMARY_SUCCESS'
)
