export const SIGN_IN = 'sign_in'
export const SIGN_OUT = 'sign_out'
export const SIGN_UP = 'sign_up'
export const SIGN_IN_SUCCESS = 'sign_in_success'
export const SIGN_OUT_SUCCESS = 'sign_out_success'
export const SIGN_UP_SUCCESS = 'sign_up_success'
