version: '3.2'
services:
  api:
    build: .
    depends_on:
      - redis-db
      - mongo-db
    ports:
      - '4000:4000'
    environment:
      - MONGO_DB_HOST=mongo-db
      - REDIS_HOST=redis-db
  redis-db:
    image: redis:alpine
  mongo-db:
    image: mongo