const def = action => `AGENT/MANAGE_BOOKING/${action}`
export const FETCH_BOOKINGS = def('FETCH_BOOKINGS')
export const FETCH_BOOKINGS_SUCCESS = def('FETCH_BOOKINGS_SUCCESS')
export const SET_BOOKINGS_STATUS_VISIBILITY_FILTER = def(
  'SET_BOOKINGS_STATUS_VISIBILITY_FILTER'
)
export const SELECT_BOOKING = def('SELECT_BOOKING')
