const def = action => `COMPANY/AGENT/${action}`
export const FETCH_AGENTS = def('FETCH_AGENTS')
export const FETCH_AGENTS_SUCCESS = def('FETCH_AGENTS_SUCCESS')
export const FETCH_AGENT_CONTRACT_RATES = def('FETCH_AGENT_CONTRACT_RATES')
export const FETCH_AGENT_CONTRACT_RATES_SUCCESS = def(
  'FETCH_AGENT_CONTRACT_RATES_SUCCESS'
)
export const REQUEST_AGENT = def('REQUEST_AGENT')
export const SELECT_AGENT = def('SELECT_AGENT')
