const def = action => `COMPANY/PRINT_BUS_PATH/${action}`
export const PRINT_BUS_PATH = def('PRINT_BUS_PATH')
export const FETCH_BOOKINGS_HOTELS_SUMMARY_AND_BUS_PATHS = def(
  'FETCH_BOOKINGS_HOTELS_SUMMARY_AND_BUS_PATHS'
)
export const FETCH_BOOKINGS_HOTELS_SUMMARY_AND_BUS_PATHS_SUCCESS = def(
  'FETCH_BOOKINGS_HOTELS_SUMMARY_AND_BUS_PATHS_SUCCESS'
)
export const MANAGE_BUS_PATH = def('MANAGE_BUS_PATH')
